### ISSUE TITLE
plugin.video.tam-0.8.7 ERROR

### ISSUE THREAD

**Issue by strannik-j** [tdw1980/tdw#11]
Hi! TAM + RuTor. After update error in log:
```python
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'bencode.BTL.BTFailure'>
Error Contents: not a valid bencoded string
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.tam/main.py", line 1568, in <module>
if mode=="open" : Open(url, info, purl, engine)
File "/storage/.kodi/addons/plugin.video.tam/main.py", line 1111, in Open
L=List(url)
File "/storage/.kodi/addons/plugin.video.tam/main.py", line 1161, in List
else: return list_bencode(url)
File "/storage/.kodi/addons/plugin.video.tam/main.py", line 1191, in list_bencode
torrent = bencode.bdecode(torrent_data)
File "/storage/.kodi/addons/plugin.video.tam/bencode/__init__.py", line 68, in bdecode
raise BTFailure("not a valid bencoded string")
BTFailure: not a valid bencoded string
-->End of Python script error report<--```

**Comment by ghost** [comment]
### kinopoisk+TAM errors alert
Please correct this error.
[kodi.log](https://github.com/tdw1980/tdw/files/3875631/kodi.log)
