### ISSUE TITLE
plugin.video.Rutor

### ISSUE THREAD

**Issue by lavaed** [tdw1980/tdw#14]
Ошибка происходит на системе Ubuntu 18 kernel 4.15 kodi 18 leia при выборе фильмов в категориях Русские фильмы, Русские сериалы и мультфильмы (т.е. не находит торрент файлы), обход настроен через EmerDNS по ссылке rutor.lib.
На андройде все тоже самое работает идеально. Уважаемый подскажи в каком направлении смотреть, чтобы исправить проблему.

> ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'httplib.InvalidURL'>
                                            Error Contents: URL can't contain control characters. '/search/\xd0\xa5\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xbf' (found at least '\xd0')
                                            Traceback (most recent call last):
                                              File "/home/gosti/.kodi/addons/plugin.video.RuTor/default.py", line 1050, in <module>
                                                if mode == 'Torrents':	Torrents(info)
                                              File "/home/gosti/.kodi/addons/plugin.video.RuTor/default.py", line 777, in Torrents
                                                L=rutor.torrents(info)
                                              File "/home/gosti/.kodi/addons/plugin.video.RuTor/rutor.py", line 262, in torrents
                                                return get_list(url)
                                              File "/home/gosti/.kodi/addons/plugin.video.RuTor/rutor.py", line 111, in get_list
                                                hp=GET(url)
                                              File "/home/gosti/.kodi/addons/plugin.video.RuTor/rutor.py", line 69, in GET
                                                resp = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1235, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1202, in do_open
                                                h.request(req.get_method(), req.get_selector(), req.data, headers)
                                              File "/usr/lib/python2.7/httplib.py", line 1082, in request
                                                self._send_request(method, url, body, headers)
                                              File "/usr/lib/python2.7/httplib.py", line 1116, in _send_request
                                                self.putrequest(method, url, **skips)
                                              File "/usr/lib/python2.7/httplib.py", line 942, in putrequest
                                                self._validate_path(url)
                                              File "/usr/lib/python2.7/httplib.py", line 1032, in _validate_path
                                                raise InvalidURL(msg)
                                            InvalidURL: URL can't contain control characters. '/search/\xd0\xa5\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xbf' (found at least '\xd0')
                                            -->End of Python script error report<--
2020-08-28 14:40:04.617 T:140418553460480   ERROR: GetDirectory - Error getting plugin://plugin.video.RuTor/?id=9CC2D8EA&info=%7b%27year%27%3a%20%272019%27%2c%20%27genre%27%3a%20%27%20%5cxd0%5cx9a%5cxd0%5cxbe%5cxd0%5cxbc%5cxd0%5cxb5%5cxd0%5cxb4%5cxd0%5cxb8%5cxd1%5cx8f%27%2c%20%27fulltitle%27%3a%20%27%5cxd0%5cxa5%5cxd0%5cxbe%5cxd0%5cxbb%5cxd0%5cxbe%5cxd0%5cxbf%20(2019)%20WEB-DL%201080p%20%7c%20iTunes%27%2c%20%27id%27%3a%20%27745641%27%2c%20%27size%27%3a%20%273.58GB%27%2c%20%27plot%27%3a%20%278%20cOptions(1451376%2c3470624)%3b%5cxd0%5cx9e%5cxd0%5cxbf%5cxd0%5cxb8%5cxd1%5cx81%5cxd0%5cxb0%5cxd0%5cxbd%5cxd0%5cxb8%5cxd0%5cxb5%20%5cxd0%5cxb8%20%5cxd0%5cxbf%5cxd0%5cxbe%5cxd1%5cx81%5cxd1%5cx82%5cxd0%5cxb5%5cxd1%5cx80%20%5cxd1%5cx82%5cxd0%5cxb0%5cxd0%5cxba%5cxd0%5cxbe%5cxd0%5cxb5%20%5cxd0%5cxba%5cxd0%5cxbe%5cxd0%5cxbd%5cxd0%5cxb5%5cxd1%5cx87%5cxd0%5cxbd%5cxd0%5cxbe%2c%20%5cxd0%5cxbd%5cxd0%5cxbe%20%5cxd0%5cxba%5cxd0%5cxb0%5cxd0%5cxba%20%5cxd1%5cx8f%20%5cxd0%5cxbf%5cxd0%5cxbe%5cxd0%5cxbd%5cxd1%5cx8f%5cxd0%5cxbb%20%5cxd1%5cx8d%5cxd1%5cx82%5cxd0%5cxbe%20%5cxd1%5cx82%5cxd0%5cxbe%5cxd1%5cx82%20%5cxd1%5cx84%5cxd0%5cxb8%5cxd0%5cxbb%5cxd1%5cx8c%5cxd0%5cxbc%20%5cxd0%5cxba%5cxd0%5cxbe%5cxd1%5cx82%5cxd0%5cxbe%5cxd1%5cx80%5cxd1%5cx8b%5cxd0%5cxb9%20%5cxd1%5cx81%5cxd0%5cxbe%5cxd0%5cxb1%5cxd1%5cx80%5cxd0%5cxb0%5cxd0%5cxbb%20%5cxd0%5cxb2%20%5cxd0%5cxbf%5cxd1%5cx80%5cxd0%5cxbe%5cxd0%5cxba%5cxd0%5cxb0%5cxd1%5cx82%5cxd0%5cxb5%203%20%5cxd0%5cxbc%5cxd0%5cxbb%5cxd1%5cx80%5cxd0%5cxb4%20%5cxd1%5cx80%5cxd1%5cx83%5cxd0%5cxb1%5cxd0%5cxbb%5cxd0%5cxb5%5cxd0%5cxb9%20%5cxd0%5cxb8%20%5cxd1%5cx81%5cxd1%5cx82%5cxd0%5cxb0%5cxd0%5cxbb%20%5cxd0%5cxbe%5cxd0%5cxb4%5cxd0%5cxbd%5cxd0%5cxb8%5cxd0%5cxbc%20%5cxd0%5cxb8%5cxd0%5cxb7%20%5cxd0%5cxbb%5cxd0%5cxb8%5cxd0%5cxb4%5cxd0%5cxb5%5cxd1%5cx80%5cxd0%5cxbe%5cxd0%5cxb2%20%5cxd1%5cx81%5cxd0%5cxb1%5cxd0%5cxbe%5cxd1%5cx80%5cxd0%5cxbe%5cxd0%5cxb2%20%5cxd0%5cxb2%20%5cxd0%5cxb8%5cxd1%5cx81%5cxd1%5cx82%5cxd0%5cxbe%5cxd1%5cx80%5cxd0%5cxb8%5cxd0%5cxb8.%20%5cxd0%5cx92%5cxd0%5cxbe%5cxd0%5cxb1%5cxd1%5cx89%5cxd0%5cxb5%5cxd0%5cxbc%20%20%5cxd0%5cxbc%5cxd0%5cxbe%5cxd0%5cxb6%5cxd0%5cxbd%5cxd0%5cxbe%20%5cxd0%5cxbe%5cxd0%5cxb7%5cxd0%5cxbd%5cxd0%5cxb0%5cxd0%5cxba%5cxd0%5cxbe%5cxd0%5cxbc%5cxd0%5cxb8%5cxd1%5cx82%5cxd1%5cx8c%5cxd1%5cx81%5cxd1%5cx8f)%26nbsp%3balcogleb%2027-02-2020%200%3a48%3a13%20(6%20%5cxd0%5cxbc%5cxd0%5cxb5%5cxd1%5cx81%5cxd1%5cx8f%5cxd1%5cx86%5cxd0%5cxb5%5cxd0%5cxb2%20%5cxd0%5cxbd%5cxd0%5cxb0%5cxd0%5cxb7%5cxd0%5cxb0%5cxd0%5cxb4)%20%5cxd0%5cx9e%5cxd1%5cx86%5cxd0%5cxb5%5cxd0%5cxbd%5cxd0%5cxb8%5cxd0%5cxbb%20%5cxd0%5cxbd%5cxd0%5cxb0%3a%2010%20cOptions(839633%2c3470621)%3b%5cxd0%5cx9e%5cxd1%5cx82%5cxd0%5cxbb%5cxd0%5cxb8%5cxd1%5cx87%5cxd0%5cxbd%5cxd0%5cxb0%5cxd1%5cx8f%20%5cxd0%5cxba%5cxd0%5cxbe%5cxd0%5cxbc%5cxd0%5cxb5%5cxd0%5cxb4%5cxd0%5cxb8%5cxd1%5cx8f%20%5cxd0%5cxbd%5cxd0%5cxb0%208%20%5cxd0%5cxb8%5cxd0%5cxb7%2010%20(%5cxd0%5cxbe%5cxd1%5cx81%5cxd0%5cxbe%5cxd0%5cxb1%5cxd0%5cxb5%5cxd0%5cxbd%5cxd0%5cxbd%5cxd0%5cxbe%20%5cxd1%5cx83%5cxd1%5cx87%5cxd0%5cxb8%5cxd1%5cx82%5cxd1%5cx8b%5cxd0%5cxb2%5cxd0%5cxb0%5cxd1%5cx8f%2c%20%5cxd1%5cx87%5cxd1%5cx82%5cxd0%5cxbe%20%5cxd1%5cx8d%5cxd1%5cx82%5cxd0%5cxbe%20%5cxd0%5cxbd%5cxd0%5cxb0%5cxd1%5cx88%20%5cxd1%5cx84%5cxd0%5cxb8%5cxd0%5cxbb%5cxd1%5cx8c%5cxd0%5cxbc!)%26nbsp%3blexx256%2027-02-2020%200%3a10%3a18%20(6%20%5cxd0%5cxbc%5cxd0%5cxb5%5cxd1%5cx81%5cxd1%5cx8f%5cxd1%5cx86%5cxd0%5cxb5%5cxd0%5cxb2%20%5cxd0%5cxbd%5cxd0%5cxb0%5cxd0%5cxb7%5cxd0%5cxb0%5cxd0%5cxb4)%20%20cOptions(561893%2c3470599)%3b%5cxd0%5cxba%5cxd0%5cxbe%5cxd0%5cxbc%5cxd1%5cx83%20%5cxd0%5cxb8%5cxd0%5cxbd%5cxd1%5cx82%5cxd0%5cxb5%5cxd1%5cx80%5cxd0%5cxb5%5cxd1%5cx81%5cxd0%5cxbd%5cxd0%5cxbe%20%5cxd0%5cxbc%5cxd0%5cxbe%5cxd0%5cxb6%5cxd0%5cxb5%5cxd1%5cx82%5cxd0%5cxb5%20%5cxd0%5cxb2%5cxd0%5cxbe%5cxd1%5cx82%20%5cxd1%5cx8d%5cxd1%5cx82%5cxd0%5cxb8%20%5cxd1%5cx84%5cxd0%5cxb8%5cxd0%5cxbb%5cxd1%5cx8c%5cxd0%5cxbc%5cxd1%5cx8b%20%5cxd0%5cxb3%5cxd0%5cxbb%5cxd1%5cx8f%5cxd0%5cxbd%5cxd1%5cx83%5cxd1%5cx82%5cxd1%5cx8c...%5cxd0%5cxa1%5cxd0%5cxba%5cxd1%5cx80%5cxd1%5cx8b%5cxd1%5cx82%5cxd1%5cx8b%5cxd0%5cxb9%20%5cxd1%5cx82%5cxd0%5cxb5%5cxd0%5cxba%5cxd1%5cx81%5cxd1%5cx82%27%2c%20%27title%27%3a%20%27%5cxd0%5cxa5%5cxd0%5cxbe%5cxd0%5cxbb%5cxd0%5cxbe%5cxd0%5cxbf%27%2c%20%27magnet%27%3a%20%27magnet%3a%3fxt%3durn%3abtih%3a07477f51d6a4d0827b19d85b921dd776443a5ad7%26dn%3drutor.info%26tr%3dudp%3a%2f%2fopentor.org%3a2710%26tr%3dudp%3a%2f%2fopentor.org%3a2710%26tr%3dhttp%3a%2f%2fretracker.local%2fannounce%27%2c%20%27cover%27%3a%20%27https%3a%2f%2fc.radikal.ru%2fc41%2f2002%2f2c%2fc1a900171040.jpg%27%2c%20%27originaltitle%27%3a%20%27%5cxd0%5cxa5%5cxd0%5cxbe%5cxd0%5cxbb%5cxd0%5cxbe%5cxd0%5cxbf%27%2c%20%27seeds%27%3a%20%271368%27%7d&mode=Torrents&url=745641
2020-08-28 14:40:04.627 T:140419546319040   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.RuTor/?id=9CC2D8EA&info=%7b%27year%27%3a%20%272019%27%2c%20%27genre%27%3a%20%27%20%5cxd0%5cx9a%5cxd0%5cxbe%5cxd0%5cxbc%5cxd0%5cxb5%5cxd0%5cxb4%5cxd0%5cxb8%5cxd1%5cx8f%27%2c%20%27fulltitle%27%3a%20%27%5cxd0%5cxa5%5cxd0%5cxbe%5cxd0%5cxbb%5cxd0%5cxbe%5cxd0%5cxbf%20(2019)%20WEB-DL%201080p%20%7c%20iTunes%27%2c%20%27id%27%3a%20%27745641%27%2c%20%27size%27%3a%20%273.58GB%27%2c%20%27plot%27%3a%20%278%20cOptions(1451376%2c3470624)%3b%5cxd0%5cx9e%5cxd0%5cxbf%5cxd0%5cxb8%5cxd1%5cx81%5cxd0%5cxb0%5cxd0%5cxbd%5cxd0%5cxb8%5cxd0%5cxb5%20%5cxd0%5cxb8%20%5cxd0%5cxbf%5cxd0%5cxbe%5cxd1%5cx81%5cxd1%5cx82%5cxd0%5cxb5%5cxd1%5cx80%20%5cxd1%5cx82%5cxd0%5cxb0%5cxd0%5cxba%5cxd0%5cxbe%5cxd0%5cxb5%20%5cxd0%5cxba%5cxd0%5cxbe%5cxd0%5cxbd%5cxd0%5cxb5%5cxd1%5cx87%5cxd0%5cxbd%5cxd0%5cxbe%2c%20%5cxd0%5cxbd%5cxd0%5cxbe%20%5cxd0%5cxba%5cxd0%5cxb0%5cxd0%5cxba%20%5cxd1%5cx8f%20%5cxd0%5cxbf%5cxd0%5cxbe%5cxd0%5cxbd%5cxd1%5cx8f%5cxd0%5cxbb%20%5cxd1%5cx8d%5cxd1%5cx82%5cxd0%5cxbe%20%5cxd1%5cx82%5cxd0%5cxbe%5cxd1%5cx82%20%5cxd1%5cx84%5cxd0%5cxb8%5cxd0%5cxbb%5cxd1%5cx8c%5cxd0%5cxbc%20%5cxd0%5cxba%5cxd0%5cxbe%5cxd1%5cx82%5cxd0%5cxbe%5cxd1%5cx80%5cxd1%5cx8b%5cxd0%5cxb9%20%5cxd1%5cx81%5cxd0%5cxbe%5cxd0%5cxb1%5cxd1%5cx80%5cxd0%5cxb0%5cxd0%5cxbb%20%5cxd0%5cxb2%20%5cxd0%5cxbf%5cxd1%5cx80%5cxd0%5cxbe%5cxd0%5cxba%5cxd0%5cxb0%5cxd1%5cx82%5cxd0%5cxb5%203%20%5cxd0%5cxbc%5cxd0%5cxbb%5cxd1%5cx80%5cxd0%5cxb4%20%5cxd1%5cx80%5cxd1%5cx83%5cxd0%5cxb1%5cxd0%5cxbb%5cxd0%5cxb5%5cxd0%5cxb9%20%5cxd0%5cxb8%20%5cxd1%5cx81%5cxd1%5cx82%5cxd0%5cxb0%5cxd0%5cxbb%20%5cxd0%5cxbe%5cxd0%5cxb4%5cxd0%5cxbd%5cxd0%5cxb8%5cxd0%5cxbc%20%5cxd0%5cxb8%5cxd0%5cxb7%20%5cxd0%5cxbb%5cxd0%5cxb8%5cxd0%5cxb4%5cxd0%5cxb5%5cxd1%5cx80%5cxd0%5cxbe%5cxd0%5cxb2%20%5cxd1%5cx81%5cxd0%5cxb1%5cxd0%5cxbe%5cxd1%5cx80%5cxd0%5cxbe%5cxd0%5cxb2%20%5cxd0%5cxb2%20%5cxd0%5cxb8%5cxd1%5cx81%5cxd1%5cx82%5cxd0%5cxbe%5cxd1%5cx80%5cxd0%5cxb8%5cxd0%5cxb8.%20%5cxd0%5cx92%5cxd0%5cxbe%5cxd0%5cxb1%5cxd1%5cx89%5cxd0%5cxb5%5cxd0%5cxbc%20%20%5cxd0%5cxbc%5cxd0%5cxbe%5cxd0%5cxb6%5cxd0%5cxbd%5cxd0%5cxbe%20%5cxd0%5cxbe%5cxd0%5cxb7%5cxd0%5cxbd%5cxd0%5cxb0%5cxd0%5cxba%5cxd0%5cxbe%5cxd0%5cxbc%5cxd0%5cxb8%5cxd1%5cx82%5cxd1%5cx8c%5cxd1%5cx81%5cxd1%5cx8f)%26nbsp%3balcogleb%2027-02-2020%200%3a48%3a13%20(6%20%5cxd0%5cxbc%5cxd0%5cxb5%5cxd1%5cx81%5cxd1%5cx8f%5cxd1%5cx86%5cxd0%5cxb5%5cxd0%5cxb2%20%5cxd0%5cxbd%5cxd0%5cxb0%5cxd0%5cxb7%5cxd0%5cxb0%5cxd0%5cxb4)%20%5cxd0%5cx9e%5cxd1%5cx86%5cxd0%5cxb5%5cxd0%5cxbd%5cxd0%5cxb8%5cxd0%5cxbb%20%5cxd0%5cxbd%5cxd0%5cxb0%3a%2010%20cOptions(839633%2c3470621)%3b%5cxd0%5cx9e%5cxd1%5cx82%5cxd0%5cxbb%5cxd0%5cxb8%5cxd1%5cx87%5cxd0%5cxbd%5cxd0%5cxb0%5cxd1%5cx8f%20%5cxd0%5cxba%5cxd0%5cxbe%5cxd0%5cxbc%5cxd0%5cxb5%5cxd0%5cxb4%5cxd0%5cxb8%5cxd1%5cx8f%20%5cxd0%5cxbd%5cxd0%5cxb0%208%20%5cxd0%5cxb8%5cxd0%5cxb7%2010%20(%5cxd0%5cxbe%5cxd1%5cx81%5cxd0%5cxbe%5cxd0%5cxb1%5cxd0%5cxb5%5cxd0%5cxbd%5cxd0%5cxbd%5cxd0%5cxbe%20%5cxd1%5cx83%5cxd1%5cx87%5cxd0%5cxb8%5cxd1%5cx82%5cxd1%5cx8b%5cxd0%5cxb2%5cxd0%5cxb0%5cxd1%5cx8f%2c%20%5cxd1%5cx87%5cxd1%5cx82%5cxd0%5cxbe%20%5cxd1%5cx8d%5cxd1%5cx82%5cxd0%5cxbe%20%5cxd0%5cxbd%5cxd0%5cxb0%5cxd1%5cx88%20%5cxd1%5cx84%5cxd0%5cxb8%5cxd0%5cxbb%5cxd1%5cx8c%5cxd0%5cxbc!)%26nbsp%3blexx256%2027-02-2020%200%3a10%3a18%20(6%20%5cxd0%5cxbc%5cxd0%5cxb5%5cxd1%5cx81%5cxd1%5cx8f%5cxd1%5cx86%5cxd0%5cxb5%5cxd0%5cxb2%20%5cxd0%5cxbd%5cxd0%5cxb0%5cxd0%5cxb7%5cxd0%5cxb0%5cxd0%5cxb4)%20%20cOptions(561893%2c3470599)%3b%5cxd0%5cxba%5cxd0%5cxbe%5cxd0%5cxbc%5cxd1%5cx83%20%5cxd0%5cxb8%5cxd0%5cxbd%5cxd1%5cx82%5cxd0%5cxb5%5cxd1%5cx80%5cxd0%5cxb5%5cxd1%5cx81%5cxd0%5cxbd%5cxd0%5cxbe%20%5cxd0%5cxbc%5cxd0%5cxbe%5cxd0%5cxb6%5cxd0%5cxb5%5cxd1%5cx82%5cxd0%5cxb5%20%5cxd0%5cxb2%5cxd0%5cxbe%5cxd1%5cx82%20%5cxd1%5cx8d%5cxd1%5cx82%5cxd0%5cxb8%20%5cxd1%5cx84%5cxd0%5cxb8%5cxd0%5cxbb%5cxd1%5cx8c%5cxd0%5cxbc%5cxd1%5cx8b%20%5cxd0%5cxb3%5cxd0%5cxbb%5cxd1%5cx8f%5cxd0%5cxbd%5cxd1%5cx83%5cxd1%5cx82%5cxd1%5cx8c...%5cxd0%5cxa1%5cxd0%5cxba%5cxd1%5cx80%5cxd1%5cx8b%5cxd1%5cx82%5cxd1%5cx8b%5cxd0%5cxb9%20%5cxd1%5cx82%5cxd0%5cxb5%5cxd0%5cxba%5cxd1%5cx81%5cxd1%5cx82%27%2c%20%27title%27%3a%20%27%5cxd0%5cxa5%5cxd0%5cxbe%5cxd0%5cxbb%5cxd0%5cxbe%5cxd0%5cxbf%27%2c%20%27magnet%27%3a%20%27magnet%3a%3fxt%3durn%3abtih%3a07477f51d6a4d0827b19d85b921dd776443a5ad7%26dn%3drutor.info%26tr%3dudp%3a%2f%2fopentor.org%3a2710%26tr%3dudp%3a%2f%2fopentor.org%3a2710%26tr%3dhttp%3a%2f%2fretracker.local%2fannounce%27%2c%20%27cover%27%3a%20%27https%3a%2f%2fc.radikal.ru%2fc41%2f2002%2f2c%2fc1a900171040.jpg%27%2c%20%27originaltitle%27%3a%20%27%5cxd0%5cxa5%5cxd0%5cxbe%5cxd0%5cxbb%5cxd0%5cxbe%5cxd0%5cxbf%27%2c%20%27seeds%27%3a%20%271368%27%7d&mode=Torrents&url=745641) failed

**Comment by lavaed** [comment]
Проблема появилась после обновления python2.7.15 на python2.7.17. Вернулся на старую версию и проблема ушла.
